// Stamps src/gen-build.ts with the current git short hash + UTC build time.
// Runs automatically before `npm run dev` and `npm run build` (pre-scripts),
// so the game can always display exactly which build is on screen — the
// answer to "is my phone really showing the latest version?"
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

let hash = 'dev'
try {
  hash = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
  // Never let the stamp lie: uncommitted work means the hash does NOT
  // describe the code on screen. Mark it dirty so nobody deploys it by
  // mistake (deploy rule: dirty builds never ship).
  const dirty = execSync("git status --porcelain -- . ':!src/gen-build.ts'", { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
  if (dirty) hash += '-dirty'
} catch {
  /* not a git checkout — keep "dev" */
}
const time = new Date().toISOString().replace('T', ' ').slice(0, 16) + 'Z'
writeFileSync(
  new URL('../src/gen-build.ts', import.meta.url),
  `// AUTO-GENERATED by scripts/stamp-build.mjs — do not edit by hand.\nexport const BUILD_HASH = '${hash}'\nexport const BUILD_TIME = '${time}'\n`
)
console.log(`build stamp: ${hash} (${time})`)
